server {
    listen 80;
    server_name localhost;

    # Attach authorization header on redirect
    proxy_set_header Authorization $http_authorization;

    # Start with the header sent by the mobile app
    set $user_id $http_x_user_id;

    # If the ALB provided a verified identity (Browser flow), override it
    if ($http_x_amzn_oidc_identity != "") {
        set $user_id $http_x_amzn_oidc_identity;
    }

    # Send the final result to the backend (set to 1 for testing)
    proxy_set_header X-User-Id 1;
    # proxy_set_header X-User-Id $user_id;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    location /api/map/ {
        proxy_pass http://fleet-service:8080;
    }

    location ~ ^/api/(fault|rental)/ {
        proxy_pass http://rental-service:8080;
    }

    location /api/wallet/ {
        proxy_pass http://payment-service:8080;
    }

    location /fleet/ {
        proxy_pass http://fleet-service:8080/;
        proxy_set_header X-Forwarded-Prefix /fleet;
    }

    location /rental/ {
        proxy_pass http://rental-service:8080/;
        proxy_set_header X-Forwarded-Prefix /rental;
    }

    location /payment/ {
        proxy_pass http://payment-service:8080/;
        proxy_set_header X-Forwarded-Prefix /payment;
    }

    location /fleet/v3/api-docs {
        proxy_pass http://fleet-service:8080/v3/api-docs;
    }

    location /rental/v3/api-docs {
        proxy_pass http://rental-service:8080/v3/api-docs;
    }

    location /payment/v3/api-docs {
        proxy_pass http://payment-service:8080/v3/api-docs;
    }
}