spring:
  application:
    name: payment-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${DB_DDL_AUTO}
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    consumer:
      group-id: payment-service-group
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"

springdoc:
  server:
    forward-headers-strategy: framework
  swagger-ui:
    path: /swagger-ui
    configUrl: /fleet/v3/api-docs/swagger-config
    url: /fleet/v3/api-docs